package com.wd.tech.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wd.tech.bean.User;
import com.wd.tech.bean.FindConversationList;

import com.wd.tech.dao.UserDao;
import com.wd.tech.dao.FindConversationListDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig findConversationListDaoConfig;

    private final UserDao userDao;
    private final FindConversationListDao findConversationListDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        findConversationListDaoConfig = daoConfigMap.get(FindConversationListDao.class).clone();
        findConversationListDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        findConversationListDao = new FindConversationListDao(findConversationListDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(FindConversationList.class, findConversationListDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        findConversationListDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public FindConversationListDao getFindConversationListDao() {
        return findConversationListDao;
    }

}
